# .github/workflows/docker-publish.yml
name: Publish Docker image to GHCR

on:
  push:
    branches: [ "master" ] # Trigger on pushes to the master branch
  pull_request:
    branches: [ "master" ] # Also trigger on pull requests for master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write # Grant permission to write to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./testconnectcenter.aw.net # The path to your application's directory containing the Dockerfile and source code
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/testconnectcenter.aw.net:latest
            ghcr.io/${{ github.repository_owner }}/testconnectcenter.aw.net:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max